// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmnmaemervabceqgnmqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbm1hZW1lcnZhYmNlcWdubXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTgwNDgsImV4cCI6MjA2NDc3NDA0OH0.N95URalI5yDY7fgvvLDA26R-suU9ZEpx9p_VTZLhl7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);